services:
  api:
    image: resale.api
    container_name: api
    build:
      context: .
      dockerfile: ReSale.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=resale
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'